// Code generated by "stringer -type AlignType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoAlign-0]
	_ = x[WorldAlign-1]
	_ = x[UserAlign-2]
}

const _AlignType_name = "NoAlignWorldAlignUserAlign"

var _AlignType_index = [...]uint8{0, 7, 17, 26}

func (i AlignType) String() string {
	if i >= AlignType(len(_AlignType_index)-1) {
		return "AlignType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlignType_name[_AlignType_index[i]:_AlignType_index[i+1]]
}
