// Code generated by "stringer -type AlphaUse"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blend-0]
	_ = x[Mask-1]
	_ = x[Opaque-2]
	_ = x[Legacy-3]
}

const _AlphaUse_name = "BlendMaskOpaqueLegacy"

var _AlphaUse_index = [...]uint8{0, 5, 9, 15, 21}

func (i AlphaUse) String() string {
	if i >= AlphaUse(len(_AlphaUse_index)-1) {
		return "AlphaUse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlphaUse_name[_AlphaUse_index[i]:_AlphaUse_index[i+1]]
}
