#!/bin/sh

(
	echo // Code generated by cmd.sh. DO NOT EDIT.
	echo
	echo package mt
	echo
	awk '{ print "func (*ToClt"$2") cmd() {}" }' tocltcmds
	echo
	awk '{ print "func (*ToSrv"$2") cmd() {}" }' tosrvcmds
) | gofmt >cmd.go
