#!/bin/sh

(
	echo '// Code generated by cmdno.sh; DO NOT EDIT.'
	echo
	echo package mt
	echo
	awk '{ print "func (*'$2'"$2") '$3'CmdNo() '$4' { return "$1" }" }' $1
	echo
	echo "var $6 = map[$4]func() $5{"
	awk '{ print "\t"$1": func() '$5' { return new('$2'"$2") }," }' $1
	echo }
) | gofmt >$1_cmdno.go
