// Code generated by "stringer -trimprefix Draw -type DrawType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DrawCube-0]
	_ = x[DrawNothing-1]
	_ = x[DrawLiquid-2]
	_ = x[DrawFlowing-3]
	_ = x[DrawLikeGlass-4]
	_ = x[DrawAllFaces-5]
	_ = x[DrawAllFacesOpt-6]
	_ = x[DrawTorch-7]
	_ = x[DrawSign-8]
	_ = x[DrawPlant-9]
	_ = x[DrawFence-10]
	_ = x[DrawRail-11]
	_ = x[DrawNodeBox-12]
	_ = x[DrawGlassFrame-13]
	_ = x[DrawFire-14]
	_ = x[DrawGlassFrameOpt-15]
	_ = x[DrawMesh-16]
	_ = x[DrawRootedPlant-17]
}

const _DrawType_name = "CubeNothingLiquidFlowingLikeGlassAllFacesAllFacesOptTorchSignPlantFenceRailNodeBoxGlassFrameFireGlassFrameOptMeshRootedPlant"

var _DrawType_index = [...]uint8{0, 4, 11, 17, 24, 33, 41, 52, 57, 61, 66, 71, 75, 82, 92, 96, 109, 113, 124}

func (i DrawType) String() string {
	if i >= DrawType(len(_DrawType_index)-1) {
		return "DrawType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DrawType_name[_DrawType_index[i]:_DrawType_index[i+1]]
}
