// Code generated by "stringer -trimprefix Hotbar -type HotbarParam"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HotbarSize-1]
	_ = x[HotbarImg-2]
	_ = x[HotbarSelImg-3]
}

const _HotbarParam_name = "SizeImgSelImg"

var _HotbarParam_index = [...]uint8{0, 4, 7, 13}

func (i HotbarParam) String() string {
	i -= 1
	if i >= HotbarParam(len(_HotbarParam_index)-1) {
		return "HotbarParam(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HotbarParam_name[_HotbarParam_index[i]:_HotbarParam_index[i+1]]
}
