// Code generated by "stringer -trimprefix HUD -type HUDField"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HUDPos-0]
	_ = x[HUDName-1]
	_ = x[HUDScale-2]
	_ = x[HUDText-3]
	_ = x[HUDNumber-4]
	_ = x[HUDItem-5]
	_ = x[HUDDir-6]
	_ = x[HUDAlign-7]
	_ = x[HUDOffset-8]
	_ = x[HUDWorldPos-9]
	_ = x[HUDSize-10]
	_ = x[HUDZIndex-11]
	_ = x[HUDText2-12]
	_ = x[hudMax-13]
}

const _HUDField_name = "PosNameScaleTextNumberItemDirAlignOffsetWorldPosSizeZIndexText2hudMax"

var _HUDField_index = [...]uint8{0, 3, 7, 12, 16, 22, 26, 29, 34, 40, 48, 52, 58, 63, 69}

func (i HUDField) String() string {
	if i >= HUDField(len(_HUDField_index)-1) {
		return "HUDField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HUDField_name[_HUDField_index[i]:_HUDField_index[i+1]]
}
