// Code generated by "stringer -type HUDType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImgHUD-0]
	_ = x[TextHUD-1]
	_ = x[StatbarHUD-2]
	_ = x[InvHUD-3]
	_ = x[WaypointHUD-4]
	_ = x[ImgWaypointHUD-5]
}

const _HUDType_name = "ImgHUDTextHUDStatbarHUDInvHUDWaypointHUDImgWaypointHUD"

var _HUDType_index = [...]uint8{0, 6, 13, 23, 29, 40, 54}

func (i HUDType) String() string {
	if i >= HUDType(len(_HUDType_index)-1) {
		return "HUDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HUDType_name[_HUDType_index[i]:_HUDType_index[i+1]]
}
