// Code generated by "stringer -type Interaction"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dig-0]
	_ = x[StopDigging-1]
	_ = x[Dug-2]
	_ = x[Place-3]
	_ = x[Use-4]
	_ = x[Activate-5]
}

const _Interaction_name = "DigStopDiggingDugPlaceUseActivate"

var _Interaction_index = [...]uint8{0, 3, 14, 17, 22, 25, 33}

func (i Interaction) String() string {
	if i >= Interaction(len(_Interaction_index)-1) {
		return "Interaction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interaction_name[_Interaction_index[i]:_Interaction_index[i+1]]
}
