// Code generated by "stringer -type ItemType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeItem-1]
	_ = x[CraftItem-2]
	_ = x[ToolItem-3]
}

const _ItemType_name = "NodeItemCraftItemToolItem"

var _ItemType_index = [...]uint8{0, 8, 17, 25}

func (i ItemType) String() string {
	i -= 1
	if i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
