// Code generated by "stringer -type LightBank"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Day-0]
	_ = x[Night-1]
}

const _LightBank_name = "DayNight"

var _LightBank_index = [...]uint8{0, 3, 8}

func (i LightBank) String() string {
	if i >= LightBank(len(_LightBank_index)-1) {
		return "LightBank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LightBank_name[_LightBank_index[i]:_LightBank_index[i+1]]
}
