// Code generated by "stringer -type LiquidType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotALiquid-0]
	_ = x[FlowingLiquid-1]
	_ = x[LiquidSrc-2]
}

const _LiquidType_name = "NotALiquidFlowingLiquidLiquidSrc"

var _LiquidType_index = [...]uint8{0, 10, 23, 32}

func (i LiquidType) String() string {
	if i >= LiquidType(len(_LiquidType_index)-1) {
		return "LiquidType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LiquidType_name[_LiquidType_index[i]:_LiquidType_index[i+1]]
}
