// Code generated by "stringer -linecomment -type MinimapType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoMinimap-0]
	_ = x[SurfaceMinimap-1]
	_ = x[RadarMinimap-2]
	_ = x[TextureMinimap-3]
}

const _MinimapType_name = "nonesurfaceradartexture"

var _MinimapType_index = [...]uint8{0, 4, 11, 16, 23}

func (i MinimapType) String() string {
	if i >= MinimapType(len(_MinimapType_index)-1) {
		return "MinimapType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MinimapType_name[_MinimapType_index[i]:_MinimapType_index[i+1]]
}
