#!/bin/sh

(
	echo '// Code generated by mkpktinfos.sh; DO NOT EDIT.'
	echo
	echo package mt
	echo
	awk '{
		print "func (*"$1") DefaultPktInfo() rudp.PktInfo { return rudp.PktInfo{"$2", "($3 == "unrel" ? "true" : "false")"} }"
	}' pktinfos
) | goimports >pktinfos.go
