#!/bin/sh

rm -f serialize.go

(
	echo // Code generated by mkserialize.sh. DO NOT EDIT.
	echo
	internal/mkserialize/mkserialize | goimports
) >>serialize.go.tmp &&
mv serialize.go.tmp serialize.go ||
rm serialize.go.tmp
