// Code generated by "stringer -type ModChanSig"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JoinOK-0]
	_ = x[JoinFail-1]
	_ = x[LeaveOK-2]
	_ = x[LeaveFail-3]
	_ = x[NotRegistered-4]
	_ = x[SetState-5]
}

const _ModChanSig_name = "JoinOKJoinFailLeaveOKLeaveFailNotRegisteredSetState"

var _ModChanSig_index = [...]uint8{0, 6, 14, 21, 30, 43, 51}

func (i ModChanSig) String() string {
	if i >= ModChanSig(len(_ModChanSig_index)-1) {
		return "ModChanSig(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModChanSig_name[_ModChanSig_index[i]:_ModChanSig_index[i+1]]
}
