// Code generated by "stringer -linecomment -type NodeBoxType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CubeBox-0]
	_ = x[FixedBox-1]
	_ = x[MountedBox-2]
	_ = x[LeveledBox-3]
	_ = x[ConnectedBox-4]
	_ = x[maxBox-5]
}

const _NodeBoxType_name = "CubeFixedMountedLeveledConnectedmaxBox"

var _NodeBoxType_index = [...]uint8{0, 4, 9, 16, 23, 32, 38}

func (i NodeBoxType) String() string {
	if i >= NodeBoxType(len(_NodeBoxType_index)-1) {
		return "NodeBoxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeBoxType_name[_NodeBoxType_index[i]:_NodeBoxType_index[i+1]]
}
