// Code generated by "stringer -trimprefix P1 -type Param1Type"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[P1Nothing-0]
	_ = x[P1Light-1]
}

const _Param1Type_name = "NothingLight"

var _Param1Type_index = [...]uint8{0, 7, 12}

func (i Param1Type) String() string {
	if i >= Param1Type(len(_Param1Type_index)-1) {
		return "Param1Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Param1Type_name[_Param1Type_index[i]:_Param1Type_index[i+1]]
}
