// Code generated by "stringer -linecomment -type PlayerListUpdateType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InitPlayers-0]
	_ = x[AddPlayers-1]
	_ = x[RemovePlayers-2]
}

const _PlayerListUpdateType_name = "initaddremove"

var _PlayerListUpdateType_index = [...]uint8{0, 4, 7, 13}

func (i PlayerListUpdateType) String() string {
	if i >= PlayerListUpdateType(len(_PlayerListUpdateType_index)-1) {
		return "PlayerListUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerListUpdateType_name[_PlayerListUpdateType_index[i]:_PlayerListUpdateType_index[i+1]]
}
