// Code generated by "stringer -linecomment -type SoundSrcType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoSrc-0]
	_ = x[PosSrc-1]
	_ = x[AOSrc-2]
}

const _SoundSrcType_name = "nowhereposao"

var _SoundSrcType_index = [...]uint8{0, 7, 10, 12}

func (i SoundSrcType) String() string {
	if i >= SoundSrcType(len(_SoundSrcType_index)-1) {
		return "SoundSrcType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SoundSrcType_name[_SoundSrcType_index[i]:_SoundSrcType_index[i+1]]
}
