// Code generated by cmdno.sh. DO NOT EDIT.

package mt

func (*ToCltHello) toCltCmdNo() uint16                 { return 2 }
func (*ToCltAcceptAuth) toCltCmdNo() uint16            { return 3 }
func (*ToCltAcceptSudoMode) toCltCmdNo() uint16        { return 4 }
func (*ToCltDenySudoMode) toCltCmdNo() uint16          { return 5 }
func (*ToCltDisco) toCltCmdNo() uint16                 { return 10 }
func (*ToCltBlkData) toCltCmdNo() uint16               { return 32 }
func (*ToCltAddNode) toCltCmdNo() uint16               { return 33 }
func (*ToCltRemoveNode) toCltCmdNo() uint16            { return 34 }
func (*ToCltInv) toCltCmdNo() uint16                   { return 39 }
func (*ToCltTimeOfDay) toCltCmdNo() uint16             { return 41 }
func (*ToCltCSMRestrictionFlags) toCltCmdNo() uint16   { return 42 }
func (*ToCltAddPlayerVel) toCltCmdNo() uint16          { return 43 }
func (*ToCltMediaPush) toCltCmdNo() uint16             { return 44 }
func (*ToCltChatMsg) toCltCmdNo() uint16               { return 47 }
func (*ToCltAORmAdd) toCltCmdNo() uint16               { return 49 }
func (*ToCltAOMsgs) toCltCmdNo() uint16                { return 50 }
func (*ToCltHP) toCltCmdNo() uint16                    { return 51 }
func (*ToCltMovePlayer) toCltCmdNo() uint16            { return 52 }
func (*ToCltDiscoLegacy) toCltCmdNo() uint16           { return 53 }
func (*ToCltFOV) toCltCmdNo() uint16                   { return 54 }
func (*ToCltDeathScreen) toCltCmdNo() uint16           { return 55 }
func (*ToCltMedia) toCltCmdNo() uint16                 { return 56 }
func (*ToCltNodeDefs) toCltCmdNo() uint16              { return 58 }
func (*ToCltAnnounceMedia) toCltCmdNo() uint16         { return 60 }
func (*ToCltItemDefs) toCltCmdNo() uint16              { return 61 }
func (*ToCltPlaySound) toCltCmdNo() uint16             { return 63 }
func (*ToCltStopSound) toCltCmdNo() uint16             { return 64 }
func (*ToCltPrivs) toCltCmdNo() uint16                 { return 65 }
func (*ToCltInvFormspec) toCltCmdNo() uint16           { return 66 }
func (*ToCltDetachedInv) toCltCmdNo() uint16           { return 67 }
func (*ToCltShowFormspec) toCltCmdNo() uint16          { return 68 }
func (*ToCltMovement) toCltCmdNo() uint16              { return 69 }
func (*ToCltSpawnParticle) toCltCmdNo() uint16         { return 70 }
func (*ToCltAddParticleSpawner) toCltCmdNo() uint16    { return 71 }
func (*ToCltAddHUD) toCltCmdNo() uint16                { return 73 }
func (*ToCltRmHUD) toCltCmdNo() uint16                 { return 74 }
func (*ToCltChangeHUD) toCltCmdNo() uint16             { return 75 }
func (*ToCltHUDFlags) toCltCmdNo() uint16              { return 76 }
func (*ToCltSetHotbarParam) toCltCmdNo() uint16        { return 77 }
func (*ToCltBreath) toCltCmdNo() uint16                { return 78 }
func (*ToCltSkyParams) toCltCmdNo() uint16             { return 79 }
func (*ToCltOverrideDayNightRatio) toCltCmdNo() uint16 { return 80 }
func (*ToCltLocalPlayerAnim) toCltCmdNo() uint16       { return 81 }
func (*ToCltEyeOffset) toCltCmdNo() uint16             { return 82 }
func (*ToCltDelParticleSpawner) toCltCmdNo() uint16    { return 83 }
func (*ToCltCloudParams) toCltCmdNo() uint16           { return 84 }
func (*ToCltFadeSound) toCltCmdNo() uint16             { return 85 }
func (*ToCltUpdatePlayerList) toCltCmdNo() uint16      { return 86 }
func (*ToCltModChanMsg) toCltCmdNo() uint16            { return 87 }
func (*ToCltModChanSig) toCltCmdNo() uint16            { return 88 }
func (*ToCltNodeMetasChanged) toCltCmdNo() uint16      { return 89 }
func (*ToCltSunParams) toCltCmdNo() uint16             { return 90 }
func (*ToCltMoonParams) toCltCmdNo() uint16            { return 91 }
func (*ToCltStarParams) toCltCmdNo() uint16            { return 92 }
func (*ToCltSRPBytesSaltB) toCltCmdNo() uint16         { return 96 }
func (*ToCltFormspecPrepend) toCltCmdNo() uint16       { return 97 }
func (*ToCltMinimapModes) toCltCmdNo() uint16          { return 98 }

var newToCltCmd = map[uint16]func() Cmd{
	2:  func() Cmd { return new(ToCltHello) },
	3:  func() Cmd { return new(ToCltAcceptAuth) },
	4:  func() Cmd { return new(ToCltAcceptSudoMode) },
	5:  func() Cmd { return new(ToCltDenySudoMode) },
	10: func() Cmd { return new(ToCltDisco) },
	32: func() Cmd { return new(ToCltBlkData) },
	33: func() Cmd { return new(ToCltAddNode) },
	34: func() Cmd { return new(ToCltRemoveNode) },
	39: func() Cmd { return new(ToCltInv) },
	41: func() Cmd { return new(ToCltTimeOfDay) },
	42: func() Cmd { return new(ToCltCSMRestrictionFlags) },
	43: func() Cmd { return new(ToCltAddPlayerVel) },
	44: func() Cmd { return new(ToCltMediaPush) },
	47: func() Cmd { return new(ToCltChatMsg) },
	49: func() Cmd { return new(ToCltAORmAdd) },
	50: func() Cmd { return new(ToCltAOMsgs) },
	51: func() Cmd { return new(ToCltHP) },
	52: func() Cmd { return new(ToCltMovePlayer) },
	53: func() Cmd { return new(ToCltDiscoLegacy) },
	54: func() Cmd { return new(ToCltFOV) },
	55: func() Cmd { return new(ToCltDeathScreen) },
	56: func() Cmd { return new(ToCltMedia) },
	58: func() Cmd { return new(ToCltNodeDefs) },
	60: func() Cmd { return new(ToCltAnnounceMedia) },
	61: func() Cmd { return new(ToCltItemDefs) },
	63: func() Cmd { return new(ToCltPlaySound) },
	64: func() Cmd { return new(ToCltStopSound) },
	65: func() Cmd { return new(ToCltPrivs) },
	66: func() Cmd { return new(ToCltInvFormspec) },
	67: func() Cmd { return new(ToCltDetachedInv) },
	68: func() Cmd { return new(ToCltShowFormspec) },
	69: func() Cmd { return new(ToCltMovement) },
	70: func() Cmd { return new(ToCltSpawnParticle) },
	71: func() Cmd { return new(ToCltAddParticleSpawner) },
	73: func() Cmd { return new(ToCltAddHUD) },
	74: func() Cmd { return new(ToCltRmHUD) },
	75: func() Cmd { return new(ToCltChangeHUD) },
	76: func() Cmd { return new(ToCltHUDFlags) },
	77: func() Cmd { return new(ToCltSetHotbarParam) },
	78: func() Cmd { return new(ToCltBreath) },
	79: func() Cmd { return new(ToCltSkyParams) },
	80: func() Cmd { return new(ToCltOverrideDayNightRatio) },
	81: func() Cmd { return new(ToCltLocalPlayerAnim) },
	82: func() Cmd { return new(ToCltEyeOffset) },
	83: func() Cmd { return new(ToCltDelParticleSpawner) },
	84: func() Cmd { return new(ToCltCloudParams) },
	85: func() Cmd { return new(ToCltFadeSound) },
	86: func() Cmd { return new(ToCltUpdatePlayerList) },
	87: func() Cmd { return new(ToCltModChanMsg) },
	88: func() Cmd { return new(ToCltModChanSig) },
	89: func() Cmd { return new(ToCltNodeMetasChanged) },
	90: func() Cmd { return new(ToCltSunParams) },
	91: func() Cmd { return new(ToCltMoonParams) },
	92: func() Cmd { return new(ToCltStarParams) },
	96: func() Cmd { return new(ToCltSRPBytesSaltB) },
	97: func() Cmd { return new(ToCltFormspecPrepend) },
	98: func() Cmd { return new(ToCltMinimapModes) },
}
